const PolicyPage = () => {
    return (
        <div className="max-w-4xl mx-auto p-6">
            <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
            <p className="text-sm text-gray-400 mb-6">Last updated: May 21, 2024</p>
            <p className="mb-6">
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p className="mb-6">
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
            <h2 className="text-2xl font-semibold mb-4">Interpretation and Definitions</h2>
            <h3 className="text-xl font-semibold mb-3">Interpretation</h3>
            <p className="mb-6">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>
            <h3 className="text-xl font-semibold mb-3">Definitions</h3>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
                <li><p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p></li>
                <li><p><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p></li>
                <li><p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Sonar.</p></li>
                <li><p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p></li>
                <li><p><strong>Country</strong> refers to: Vietnam</p></li>
                <li><p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p></li>
                <li><p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p></li>
                <li><p><strong>Service</strong> refers to the Website.</p></li>
                <li><p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p></li>
                <li><p><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</p></li>
                <li><p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p></li>
                <li><p><strong>Website</strong> refers to Sonar, accessible from <a href="https://sonar-musicvideo.vercel.app/" rel="external nofollow noopener" target="_blank" className="text-blue-500 hover:underline">https://sonar-musicvideo.vercel.app/</a></p></li>
                <li><p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p></li>
            </ul>
            <h2 className="text-2xl font-semibold mb-4">Collecting and Using Your Personal Data</h2>
            <h3 className="text-xl font-semibold mb-3">Types of Data Collected</h3>
            <h4 className="text-lg font-semibold mb-2">Personal Data</h4>
            <p className="mb-4">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Usage Data</li>
            </ul>
            <h4 className="text-lg font-semibold mb-2">Usage Data</h4>
            <p className="mb-6">
                Usage Data is collected automatically when using the Service.
            </p>
            <p className="mb-6">
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="mb-6">
                When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            </p>
            <p className="mb-6">
                We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
            </p>
            <h4 className="text-lg font-semibold mb-2">Information from Third-Party Social Media Services</h4>
            <p className="mb-4">
                The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:
            </p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
                <li>Google</li>
                <li>Facebook</li>
                <li>Instagram</li>
                <li>Twitter</li>
                <li>LinkedIn</li>
            </ul>
            <p className="mb-6">
                If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.
            </p>
            <p className="mb-6">
                You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.
            </p>
            <h4 className="text-lg font-semibold mb-2">Tracking Technologies and Cookies</h4>
            <p className="mb-4">
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
            </p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
                <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
            </ul>
            <p className="mb-6">
                Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies: <a href="https://www.freeprivacypolicy.com/blog/sample-privacy-policy-template/#Use_Of_Cookies_And_Tracking" target="_blank" className="text-blue-500 hover:underline">Use of Cookies by Free Privacy Policy</a>.
            </p>
            <p className="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
                <li>
                    <p className="mb-2"><strong>Necessary / Essential Cookies</strong></p>
                    <p className="text-gray-400">
                        Type: Session Cookies<br/>
                        Administered by: Us<br/>
                        Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
                    </p>
                </li>
                <li>
                    <p className="mb-2"><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
                    <p className="text-gray-400">
                        Type: Persistent Cookies<br/>
                        Administered by: Us<br/>
                        Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
                    </p>
                </li>
                <li>
                    <p className="mb-2"><strong>Functionality Cookies</strong></p>
                    <p className="text-gray-400">
                        Type: Persistent Cookies<br/>
                        Administered by: Us<br/>
                        Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
                    </p>
                </li>
                <li>
                    <p className="mb-2"><strong>Tracking and Performance Cookies</strong></p>
                    <p className="text-gray-400">
                        Type: Persistent Cookies<br/>
                        Administered by: Third-Parties<br/>
                        Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new advertisements, pages, features, or new functionality of the Website to see how our users react to them.
                    </p>
                </li>
            </ul>
            <p className="mb-6">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
        </div>
    );
};

export default PolicyPage;
