import { Button } from "@/components/ui/button";
import prisma from "../utils/db";

export default function SeedDatabase() {
    async function postData() {
        "use server";
        await prisma.song.createMany({
            data: [
                {
                    id: 0,
                    imageString: "https://i.ytimg.com/vi/zoEtcR5EW08/hqdefault.jpg",
                    title: "Chúng Ta Của Tương Lai",
                    duration: "4:36",
                    artist: "Sơn Tùng M-TP",
                    singer: "Sơn Tùng M-TP",
                    release: 2024,
                    videoSource: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/video/ChungTaCuaTuongLai.mp4",
                    album: "Chúng Ta Của Tương Lai",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/zoEtcR5EW08",
                  }, 
                  {
                    id: 1,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/nhungloihuaboquen.jpg",
                    title: "Những Lời Hứa Bỏ Quên",
                    duration: "4:19",
                    artist: "Howie @Dear Jane",
                    singer: "Vũ",
                    release: 2023,
                    videoSource: " ",
                    album: "Những Lời Hứa Bỏ Quên",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/h6RONxjPBf4",
                },
                {
                    id: 2,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/tungla.jpg",
                    title: "Từng Là",
                    duration: "4:37",
                    artist: "Vũ Cát Tường",
                    singer: "Vũ Cát Tường",
                    release: 2024,
                    videoSource: " ",
                    album: "Từng Là",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/i4qZmKSFYvI",
                },
                {
                  id: 3,
                  imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/traidat.jpg",
                  title: "Trái đất ôm Mặt Trời",
                  duration: "3:34",
                  artist: "Kai Đinh",
                  singer: "Kai Đinh - Grey D - Hoàng Thùy Linh",
                  release: 2023,
                  videoSource: "",
                  album: "Trái đất ôm Mặt Trời",
                  category: "music",
                  youtubeString: "https://www.youtube.com/embed/ohgodOTSHjA",
                },
                {
                  id: 4,
                  imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/emxinh.jpg",
                  title: "Em Xinh",
                  duration: "3:16",
                  artist: "MONO",
                  singer: "MONO",
                  release: 2023,
                  videoSource: "",
                  album: "ĐẸP",
                  category: "music",
                  youtubeString: "https://www.youtube.com/embed/rYc1UbgbMIY",
                },
                {
                  id: 5,
                  imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/khongthesay.jpg",
                  title: "Không Thể Say",
                  duration: "4:20",
                  artist: "HIEUTHUHAI",
                  singer: "HIEUTHUHAI",
                  release: 2023,
                  videoSource: "",
                  album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
                  category: "music",
                  youtubeString: "https://www.youtube.com/embed/i0nd3NPJ4MI",
                },
                {
                  id: 6,
                  imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/shhhh.jpg",
                  title: "shhhhhhh..",
                  duration: "3:57",
                  artist: "WEAN - tlinh",
                  singer: "WEAN - tlinh",
                  release: 2023,
                  videoSource: "",
                  album: "shhhhhhh..",
                  category: "music",
                  youtubeString: "https://www.youtube.com/embed/Pys2iOT9rpw",
                },
                {
                  id: 7,
                  imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/noianhngh.jpg",
                  title: "NÓI ANH NGHE ĐƯỢC KHÔNG",
                  duration: "3:40",
                  artist: "ANDIEZ",
                  singer: "ANDIEZ",
                  release: 2023,
                  videoSource: "",
                  album: "NÓI ANH NGHE ĐƯỢC KHÔNG",
                  category: "music",
                  youtubeString: "https://www.youtube.com/embed/6M7TSibpDu4",
                },
                {
                    id: 30,
                    imageString: "https://i.ytimg.com/vi/JlZnvyBqceY/hqdefault.jpg",
                    title: "Speak Now (Taylor's Version)",
                    duration: "4:06",
                    artist: "Taylor Swift",
                    singer: "Taylor Swift",
                    release: 2023,
                    videoSource: "",
                    album: "Taylor Swift - Speak Now (Taylor's Version)",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/JlZnvyBqceY",
                  },
                  {
                    id: 31,
                    imageString: "https://i.ytimg.com/vi/8AR1dKawCi8/hqdefault.jpg",
                    title: "Mean (Taylor's Version)",
                    duration: "4:03",
                    artist: "Taylor Swift",
                    singer: "Taylor Swift",
                    release: 2023,
                    videoSource: "",
                    album: "Taylor Swift - Speak Now (Taylor's Version)",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/8AR1dKawCi8",
                  },
                  {
                    id: 32,
                    imageString: "https://i.ytimg.com/vi/pRhWAXg4xek/hqdefault.jpg",
                    title: "The Story Of Us (Taylor's Version)",
                    duration: "4:32",
                    artist: "Taylor Swift",
                    singer: "Taylor Swift",
                    release: 2023,
                    videoSource: "",
                    album: "Taylor Swift - Speak Now (Taylor's Version)",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/pRhWAXg4xek",
                  },
                  {
                    id: 33,
                    imageString: "https://i.ytimg.com/vi/maEVfpxDB8k/hqdefault.jpg",
                    title: "Never Grow Up (Taylor's Version)",
                    duration: "4:57",
                    artist: "Taylor Swift",
                    singer: "Taylor Swift",
                    release: 2023,
                    videoSource: "",
                    album: "Taylor Swift - Speak Now (Taylor's Version)",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/maEVfpxDB8k",
                  },
                  {
                    id: 34,
                    imageString: "https://i.ytimg.com/vi/mvVBuG4IOW4/hqdefault.jpg",
                    title: "Shake It Off (Taylor's Version)",
                    duration: "3:45",
                    artist: "Taylor Swift",
                    singer: "Taylor Swift",
                    release: 2023,
                    videoSource: "",
                    album: "1989 (Taylor's Version)",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/mvVBuG4IOW4",
                  },
                  {
                    id: 35,
                    imageString: "https://i.ytimg.com/vi/89aQIli8aVU/hqdefault.jpg",
                    title: "I Wish You Would (Taylor's Version)",
                    duration: "3:33",
                    artist: "Taylor Swift",
                    singer: "Taylor Swift",
                    release: 2023,
                    videoSource: "",
                    album: "1989 (Taylor's Version)",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/89aQIli8aVU",
                  },
                  {
                    id: 36,
                    imageString: "https://i.ytimg.com/vi/lUvBk4owRNU/hqdefault.jpg",
                    title: "Bad Blood (Taylor's Version)",
                    duration: "3:37",
                    artist: "Taylor Swift",
                    singer: "Taylor Swift",
                    release: 2023,
                    videoSource: "",
                    album: "1989 (Taylor's Version)",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/lUvBk4owRNU",
                  },
                  {
                    id: 37,
                    imageString: "https://i.ytimg.com/vi/vtW_4j7SsZk/hqdefault.jpg",
                    title: "Wildest Dreams (Taylor's Version)",
                    duration: "3:46",
                    artist: "Taylor Swift",
                    singer: "Taylor Swift",
                    release: 2023,
                    videoSource: "",
                    album: "1989 (Taylor's Version)",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/vtW_4j7SsZk",
                  },
                  {
                    id: 11,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/ost_qot.jpg",
                    title: "Tell Me It's Not a Dream",
                    duration: "3:56",
                    artist: "10CM",
                    singer: "10CM",
                    release: 2024,
                    videoSource: " ",
                    album: "Queen of Tears",
                    category: "ost",
                    youtubeString: "https://www.youtube.com/embed/_j0BOGdmh38",
                  },  
                  {
                    id: 12,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/latmat.jpg",
                    title: "Vẽ Lại Bức Tranh Của Mẹ",
                    duration: "4:59",
                    artist: "Bùi Anh Tuấn",
                    singer: "Bùi Anh Tuấn",
                    release: 2024,
                    videoSource: "",
                    album: "Lật Mặt 7: Một Điều Ước",
                    category: "ost",
                    youtubeString: "https://www.youtube.com/embed/0J51aUryra4",
                  },
                  {
                    id: 13,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/ducondalonkhon.jpg",
                    title: "Dù Con Đã Lớn Khôn",
                    duration: "4:08",
                    artist: "Yuno BigBoi - Lý Anh Khoa",
                    singer: "Yuno BigBoi x Tổng Đài",
                    release: 2024,
                    videoSource: "",
                    album: "Lật Mặt 7: Một Điều Ước",
                    category: "ost",
                    youtubeString: "https://www.youtube.com/embed/MgvA7ANFK4k",
                  },
                  {
                    id: 14,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/thislove.jpg",
                    title: "This Love",
                    duration: "3:49",
                    artist: "DAVICHI(다비치)",
                    singer: "DAVICHI(다비치)",
                    release: 2016,
                    videoSource: "",
                    album: "Descendants of the Sun OST",
                    category: "ost",
                    youtubeString: "https://www.youtube.com/embed/XyzaMpAVm3s",
                  },
                  {
                    id: 21,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/podcast1.jpg",
                    title: "Yêu hay nghỉ?",
                    duration: "13:16",
                    artist: "Đặng Phương Linh",
                    singer: "Đặng Phương Linh",
                    release: 2023,
                    videoSource: "",
                    album: "Podcast Chữa Lành",
                    category: "podcast",
                    youtubeString: "https://www.youtube.com/embed/Bw6Ii3TleDk",
                  },
                  {
                    id: 22,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/hoctap.jpg",
                    title: "Học hành vất vả, kết quả ngọt bùi",
                    duration: "18:48",
                    artist: "Tun Cảm Ơn",
                    singer: "Tun Cảm Ơn",
                    release: 2023,
                    videoSource: "",
                    album: "ĐCNNTK",
                    category: "podcast",
                    youtubeString: "https://www.youtube.com/embed/D7XwDaVgHMg",
                  },
                  {
                    id: 51,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/maestro.jpg",
                    title: "MAESTRO",
                    duration: "4:11",
                    artist: "SEVENTEEN (세븐틴)",
                    singer: "SEVENTEEN (세븐틴)",
                    release: 2024,
                    videoSource: "",
                    album: "SEVENTEEN BEST ALBUM '17 IS RIGHT HERE'",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/ThI0pBAbFnk",
                  },
                  {
                    id: 52,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/spot.jpg",
                    title: "SPOT!",
                    duration: "3:12",
                    artist: "ZICO (지코)",
                    singer: "ZICO (지코) - JENNIE",
                    release: 2024,
                    videoSource: "",
                    album: "SPOT!",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/xfqBQ2XhBCg",
                  },
                  {
                    id: 53,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/magnetic.jpg",
                    title: "Magnetic",
                    duration: "3:08",
                    artist: "ILLIT (아일릿)",
                    singer: "ILLIT (아일릿)",
                    release: 2024,
                    videoSource: "",
                    album: "SUPER REAL ME",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/Vk5-c_v4gMU",
                  },
                  {
                    id: 54,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/smart.jpg",
                    title: "Smart",
                    duration: "3:14",
                    artist: "LE SSERAFIM (르세라핌)",
                    singer: "LE SSERAFIM (르세라핌)",
                    release: 2024,
                    videoSource: "",
                    album: "EASY",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/KNexS61fjus",
                  },
                  {
                    id: 55,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/dna.jpg",
                    title: "DNA",
                    duration: "4:15",
                    artist: "BTS (방탄소년단)",
                    singer: "BTS (방탄소년단)",
                    release: 2018,
                    videoSource: "",
                    album: "Love Yourself 'Answer'",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/MBdVXkSdhwU",
                  },
                  {
                    id: 56,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/fakelove.jpg",
                    title: "FAKE LOVE",
                    duration: "5:18",
                    artist: "BTS (방탄소년단)",
                    singer: "BTS (방탄소년단)",
                    release: 2019,
                    videoSource: "",
                    album: "Love Yourself 'Tear'",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/7C2z4GqqS5E",
                  },
                  {
                    id: 57,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/feels.jpg",
                    title: "The Feels",
                    duration: "3:51",
                    artist: "TWICE",
                    singer: "TWICE",
                    release: 2022,
                    videoSource: "",
                    album: "The Feels",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/f5_wn8mexmM",
                  },
                  {
                    id: 41,
                    imageString: "https://i.ytimg.com/vi/32sYGCOYJUM/hqdefault.jpg",
                    title: "CHẠY NGAY ĐI (RUN NOW)",
                    duration: "4:33",
                    artist: "Sơn Tùng M-TP",
                    singer: "Sơn Tùng M-TP",
                    release: 2019,
                    videoSource: "",
                    album: "CHẠY NGAY ĐI",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/32sYGCOYJUM",
                  },
                  {
                    id: 42,
                    imageString: "https://i.ytimg.com/vi/6t-MjBazs3o/hqdefault.jpg",
                    title: "CÓ CHẮC YÊU LÀ ĐÂY",
                    duration: "3:35",
                    artist: "Sơn Tùng M-TP",
                    singer: "Sơn Tùng M-TP",
                    release: 2021,
                    videoSource: "",
                    album: "CÓ CHẮC YÊU LÀ ĐÂY",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/6t-MjBazs3o",
                  },
                  {
                    id: 43,
                    imageString: "https://i.ytimg.com/vi/Llw9Q6akRo4/hqdefault.jpg",
                    title: "LẠC TRÔI",
                    duration: "4:32",
                    artist: "Sơn Tùng M-TP",
                    singer: "Sơn Tùng M-TP",
                    release: 2017,
                    videoSource: "",
                    album: "LẠC TRÔI",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/Llw9Q6akRo4",
                  },
                  {
                    id: 44,
                    imageString: "https://i.ytimg.com/vi/knW7-x7Y7RE/hqdefault.jpg",
                    title: "HÃY TRAO CHO ANH",
                    duration: "4:22",
                    artist: "Sơn Tùng M-TP",
                    singer: "Sơn Tùng M-TP",
                    release: 2020,
                    videoSource: "",
                    album: "HÃY TRAO CHO ANH",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/knW7-x7Y7RE",
                  },
                  {
                    id: 45,
                    imageString: "https://i.ytimg.com/vi/FN7ALfpGxiI/hqdefault.jpg",
                    title: "NƠI NÀY CÓ ANH",
                    duration: "4:38",
                    artist: "Sơn Tùng M-TP",
                    singer: "Sơn Tùng M-TP",
                    release: 2017,
                    videoSource: "",
                    album: "NƠI NÀY CÓ ANH",
                    category: "music",
                    youtubeString: "https://www.youtube.com/embed/FN7ALfpGxiI",
                  },
                  {
                    id: 100,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/playlist_qot.jpg",
                    title: "QUEEN OF TEARS OST",
                    duration: "50:44",
                    artist: "None",
                    singer: "Full Soundtrack",
                    release: 2024,
                    category: "playlist",
                    videoSource: "",
                    album: "QUEEN OF TEARS",
                    youtubeString: "https://www.youtube.com/embed/LEHkP0eF5iw",
                  },    
                  {
                    id: 101,
                    imageString: "https://bcrxqnfmoeygfezttpeo.supabase.co/storage/v1/object/public/song%20image/lofichill.jpg",
                    title: "Nhạc Lofi Chill Buồn Nhất 2022",
                    duration: "47:53",
                    artist: "None",
                    singer: "Những Bản Lofi Việt Nhẹ Nhàng Cực Chill",
                    release: 2022,
                    category: "playlist",
                    videoSource: "",
                    album: "Lofi Gây Nghiện Hot Nhất",
                    youtubeString: "https://www.youtube.com/embed/2KPbAw2FpQI",
                  },                                                                     
            ],
        });
    }

    return (
        <div className="m-5">
            <form action={postData}>
                <Button type="submit">Submit</Button>
            </form>
        </div>
    )
}